# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-beamdimension

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    BeamDimension
Version:    0.4
Release:    2
Group:      Applications/Engineering
License:    GPLv3
URL:        https://github.com/poetaster/harbour-beamdimension
Source0:    %{name}-%{version}.tar.bz2
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils

%description
An app for obtaining the dimensions of beam materials under loads

%if "%{?vendor}" == "chum"
Packagename: BeamDimension
Category: Applications/Engineering
Repo: https://github.com/poetaster/harbour-beamdimension
Icon: https://raw.githubusercontent.com/poetaster/harbour-beamdimension/master/icons/172x172/harbour-beamdimension.png
Screenshots:
- https://raw.githubusercontent.com/poetaster/harbour-beamdimension/main/screenshot-1.png
- https://raw.githubusercontent.com/poetaster/harbour-beamdimension/main/screenshot-2.png
- https://raw.githubusercontent.com/poetaster/harbour-beamdimension/main/screenshot-3.png
- https://raw.githubusercontent.com/poetaster/harbour-beamdimension/main/screenshot-4.png
Forum: https://github.com/poetaster/harbour-beamdimension/discussions
Issues: https://github.com/poetaster/harbour-beamdimension/issues
Donation: https://www.paypal.me/poetasterFOSS
%endif

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
